version: '3'
services:
  mozi:
    build: backend/
    ports:
      - "5000:5000"
    links:
      - relex
      - mongo
      - redis
      - frontend
      - postgres
    volumes:
      - $MOZI_BACKEND:/root/mozi/
      - $GHOST_DIR:/root/ghost/
      - $BIODATA_DIR:/root/bio-data/
      - $DATASETS_DIR:/root/mozi_datasets
    
    working_dir: /root/mozi

    environment:
      - MONGODB_URI=mongodb://mongo:27017/
      - DATASETS_DIR=/root/mozi_datasets
      - REDIS_URI=redis://redis:6379/0
      - C_FORCE_ROOT=1
    command: bash -c "pip install -r requirements.txt && gunicorn --worker-class eventlet -b 127.0.0.1:5000 -t 300  wsgi:app"  
    security_opt:
      - seccomp=unconfined 
  
  frontend:
    build: frontend/
    volumes:
       - $MOZI_FRONTEND:/root/mozi
    ports:
       - "4200:4200"
    working_dir: /root/mozi
    command: bash -c "npm install && nodemon server.js"
  
  relex:
    image: opencog/relex
    ports:
      - "4444:4444"
    command: /bin/sh -c "./opencog-server.sh"
  
  mongo:
    image: mongo
    
   # volumes:
   #  - $MONGODB_DIR:/data/db
    ports:
     - "27017:27017"
  redis:
    image: redis
    ports:
     - "6379:6379"
  postgres:
    build: postgres/
    ports:
      - "5432:5432"
