version: '3'
services:
  mozi:
    build: backend/
    ports:
      - "5000:5000"
    links:
      - relex
      - mongo
      - redis
      - frontend
  
  frontend:
    build: frontend/
    volumes:
       - ../mozi:/root/mozi
    ports:
       - "4200:4200"
    working_dir: /root/mozi
    command: bash -c "npm install && ng serve"
  
  relex:
    image: opencog/relex
    ports:
      - "4444:4444"
    command: /bin/sh -c "./opencog-server.sh"
  
  mongo:
    image: mongo
  
  redis:
    image: redis
