version: '3'
services:
  mozi:
    image: xabush/mozi_backend
    ports:
      - "5000:5000"
    links:
      - relex
      - mongo
      - redis
      - frontend
    volumes:
      - $MOZI_BACKEND:/root/mozi/
      - $GHOST_DIR:/root/ghost/
      - $BIODATA_DIR:/root/bio-data/
      - $DATASETS_DIR:/root/mozi_datasets
    
    working_dir: /root/mozi

    environment:
      - MONGODB_URI=mongodb://mongo:27017/
      - DATASETS_DIR=/root/mozi_datasets
      - REDIS_URI=redis://redis:6379/0
      - C_FORCE_ROOT=1
    command: bash -c "pip install -r requirements.txt && gunicorn --worker-class eventlet -b 0.0.0.0:5000 -t 300  wsgi:app"  

  
  frontend:
    image: xabush/mozi_frontend
    volumes:
       - $MOZI_FRONTEND:/root/mozi
    ports:
       - "4200:4200"
    working_dir: /root/mozi
    command: bash -c "npm install && nodejs node_modules/node-sass/scripts/install.js && npm rebuild node-sass && ng build --prod && nodemon server.js"
  
  relex:
    image: opencog/relex
    ports:
      - "4444:4444"
    command: /bin/sh -c "./opencog-server.sh"
  
  mongo:
    image: mongo
    
   # volumes:
   #  - $MONGODB_DIR:/data/db
    ports:
     - "27017:27017"
  redis:
    image: redis
    ports:
     - "6379:6379"
