version: '3'
services:
  mozi:
    build: backend/
    ports:
      - "5000:5000"
    links:
      - relex
      - mongo
      - redis
      - frontend
    volumes:
      - $MOZI_BACKEND:/root/mozi/
    
    working_dir: /root/mozi

    environment:
      - MONGODB_URI=mongodb://mongo:27017/
      - REDIS_URI=redis://redis:6379/0
      - C_FORCE_ROOT=1
    command: bash -c "pip install -r requirements.txt && python wsgi.py"  
  frontend:
    build: frontend/
    volumes:
       - $MOZI_FRONTEND:/root/mozi
    ports:
       - "4200:4200"
    working_dir: /root/mozi
    command: bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
  
  relex:
    image: opencog/relex
    ports:
      - "4444:4444"
    command: /bin/sh -c "./opencog-server.sh"
  
  mongo:
    image: mongo
    ports:
     - "27017:27017"
  redis:
    image: redis
    ports:
     - "6379:6379"
