mozi:
  build: backend/
  volumes:
    - MOZI_BACKEND_DIR:/root/mozi_backend
    - /etc/localtime:/etc/localtime:ro
  environment:
    - PYTHONPATH=/usr/local/lib/python2.7/dist-packages

  command: bash

  links:
    - frontend
    - relex
    - mongo
    - redis
    - opencog

frontend:
  build: frontend/
  command: /bin/bash -c ng serve

relex:
  image: opencog/relex
  ports:
    - "4444:4444"
  command: /bin/sh -c "./opencog-server.sh"

opencog:
  image: opencog/opencong

mongo:
  image: mongo

redis:
  image: redis
